# 23/30 Sklearn : Feature Selection

In [23]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd



import matplotlib as mpl

from sklearn.model_selection import train_test_split
from keras.preprocessing.sequence import TimeseriesGenerator
from sklearn.preprocessing import MinMaxScaler, StandardScaler
import tensorflow as tf

mpl.rcParams['figure.figsize']=[10,8]
mpl.rcParams['axes.grid']=False

ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`

## 1. Variance Threshold

In [19]:
from sklearn.feature_selection import VarianceThreshold

In [22]:
from sklearn.datasets import load_iris
# importer la base de données
db =pd.read_csv('Tout.csv', sep=";" ,encoding = "ISO-8859-1")
db=db.drop(['Température Sèche Air Extérieur'],axis=1)
db_Meteo =pd.read_csv('Meteo2002.csv', sep=";" ,encoding = "ISO-8859-1")
db=db.stack().str.replace(',','.').unstack()
db_Meteo=db_Meteo.stack().str.replace(',','.').unstack()
db1=pd.merge(db_Meteo,db, on='Date/Heure')

db1=db1.drop(['Date/Heure'],axis=1)
db_date=db['Date/Heure']
db1=db1.iloc[1:]
db1.iloc[:,:] = db1.iloc[:,:].astype(float)

# periode avril octobre
db1=db1[2200:6600]

# préparation de la base de données
target="Température d'air"
df=db1.iloc[:,[0,1,2,3,4,5,13,15,21,24]]
df=db1
df['Date']=db['Date/Heure']
#X=db.drop([target],axis=1)
iris = load_iris()
X = df[[ 'Température Sèche Air Extérieur',
       'Température Point de rosée Air Extérieur', 'Solaire Direct Normal',
       'Solaire Diffus Horizontal', 'Vitesse Vent', 'Direction Vent',
       'Pression Atmosphérique', 'Altitude Solaire', 'Azimut Solaire',
       'Vitrage', 'Murs', 'Planchers sur terre-plein', 'Toits',
       'Vent Méca + Vent Nat Ext + Infiltration', 'Infiltration extérieure',
       'Chauffage de zone', 'Eclairage général', 'Informatiques + Equip.',
       'Occupation', 'Apports solaires Fenêtres extérieures',
       'Chaleur sensible zone', 'Température radiante',
       'Température opérative', 'Electricité pour la zone', 'Eclairage',
       'Chauffage (Gaz)', 'ECS (Gaz)']]
y = df["Température d'air"]

scaler=MinMaxScaler()
data_scaled=scaler.fit_transform(X)

plt.plot(X)
plt.legend()

NameError: name 'MinMaxScaler' is not defined

In [8]:
X.var(axis=0)

Température Sèche Air Extérieur                 27.064851
Température Point de rosée Air Extérieur        15.073822
Solaire Direct Normal                            0.053486
Solaire Diffus Horizontal                        0.015659
Vitesse Vent                                     3.753340
Direction Vent                               11968.589441
Pression Atmosphérique                      411248.951725
Altitude Solaire                               896.129532
Azimut Solaire                               11639.453561
Vitrage                                          0.026032
Murs                                             0.410103
Planchers sur terre-plein                        0.076169
Toits                                            0.039859
Vent Méca + Vent Nat Ext + Infiltration          6.422810
Infiltration extérieure                          0.585837
Chauffage de zone                                0.000004
Eclairage général                                0.330927
Informatiques 

In [9]:
selector = VarianceThreshold(threshold=0.2)
selector.fit(X)

VarianceThreshold(threshold=0.2)

In [10]:
selector.get_support()

array([ True,  True, False, False,  True,  True,  True,  True,  True,
       False,  True, False, False,  True,  True, False,  True, False,
       False,  True, False,  True,  True, False,  True, False, False])

In [12]:
np.array(x)[selector.get_support()]

NameError: name 'x' is not defined

In [13]:
selector.variances_

array([2.70587003e+01, 1.50703958e+01, 5.34737695e-02, 1.56554885e-02,
       3.75248723e+00, 1.19658693e+04, 4.11155486e+05, 8.95925866e+02,
       1.16368082e+04, 2.60256262e-02, 4.10009303e-01, 7.61513605e-02,
       3.98502713e-02, 6.42135002e+00, 5.85703924e-01, 3.75346462e-06,
       3.30852198e-01, 6.78178369e-02, 7.48311633e-03, 4.86294992e-01,
       5.20280846e-06, 2.09357745e+01, 2.21768491e+01, 6.78178369e-02,
       3.30852198e-01, 8.88390605e-06, 1.74534031e-03])

## 2. SelectKBest

In [14]:
from sklearn.feature_selection import SelectKBest, chi2, f_classif

In [15]:
chi2(X, y)

ValueError: Input X must be non-negative.

In [ ]:
selector = SelectKBest(f_classif, k=2)
selector.fit(X, y)
selector.scores_

array([ 119.26450218,   49.16004009, 1180.16118225,  960.0071468 ])

In [16]:
X

Température Sèche Air Extérieur  \
2201                           18.825   
2202                           19.000   
2203                           17.575   
2204                           15.525   
2205                           14.250   
...                               ...   
6596                           14.150   
6597                           12.500   
6598                           11.100   
6599                           10.950   
6600                           10.250   

      Température Point de rosée Air Extérieur  Solaire Direct Normal  \
2201                                    10.850                0.57175   
2202                                    10.250                0.31750   
2203                                    10.375                0.07275   
2204                                    10.125                0.00000   
2205                                    10.000                0.00000   
...                                        ...                    ...   
6596                                     9.050                0.00000   
6597                                     9.000                0.00000   
6598                                     8.775                0.00000   
6599                                     8.925                0.00000   
6600                                     9.000                0.00000   

      Solaire Diffus Horizontal  Vitesse Vent  Direction Vent  \
2201                    0.11650         2.100            75.0   
2202                    0.10600         2.100            65.0   
2203                    0.05425         2.850            52.5   
2204                    0.00350         2.350            50.0   
2205                    0.00000         2.100            50.0   
...                         ...           ...             ...   
6596                    0.00000         1.000           300.0   
6597                    0.00000         1.375           330.0   
6598                    0.00000         1.950           347.5   
6599                    0.00000         1.650           177.5   
6600                    0.00000         1.950           330.0   

      Pression Atmosphérique  Altitude Solaire  Azimut Solaire   Vitrage  ...  \
2201                102325.0         27.406860        244.7405  0.011953  ...   
2202                102300.0         17.792920        257.1830 -0.085894  ...   
2203                102300.0          7.702302        268.5235 -0.194886  ...   
2204                102225.0         -2.442530        279.5419 -0.263089  ...   
2205                102200.0        -12.255780        290.9393 -0.271296  ...   
...                      ...               ...             ...       ...  ...   
6596                102075.0        -10.716570        276.8122 -0.503334  ...   
6597                102175.0        -20.639460        288.4937 -0.516947  ...   
6598                102275.0        -29.854850        301.5878 -0.534055  ...   
6599                102300.0        -37.732440        316.9678 -0.524932  ...   
6600                102375.0        -43.412260        335.2629 -0.534308  ...   

      Informatiques + Equip.  Occupation  \
2201                0.564960    0.161021   
2202                0.564960    0.081274   
2203                0.564960    0.000000   
2204                0.030474    0.000000   
2205                0.030474    0.000000   
...                      ...         ...   
6596                0.030474    0.000000   
6597                0.030474    0.000000   
6598                0.030474    0.000000   
6599                0.030474    0.000000   
6600                0.030474    0.000000   

      Apports solaires Fenêtres extérieures  Chaleur sensible zone  \
2201                               1.235315                    0.0   
2202                               0.587633                    0.0   
2203                               0.191388                    0.0   
2204                               0.011095                    0.0   
220

In [ ]:
np.array(iris.feature_names)[selector.get_support()]

array(['petal length (cm)', 'petal width (cm)'], dtype='<U17')

## 3. Recursive feature Elimination

In [ ]:
from sklearn.feature_selection import RFECV
from sklearn.linear_model import SGDClassifier

In [ ]:
selector = RFECV(SGDClassifier(random_state=0), step=1, min_features_to_select=2, cv=5)
selector.fit(X, y)
print(selector.ranking_)
print(selector.grid_scores_)

[2 1 1 1]
[0.8        0.84666667 0.77333333]


In [ ]:
np.array(iris.feature_names)[selector.get_support()]

array(['sepal width (cm)', 'petal length (cm)', 'petal width (cm)'],
      dtype='<U17')

## 4. SelectFromModel

In [ ]:
from sklearn.feature_selection import SelectFromModel

In [ ]:
X = iris.data
y = iris.target
selector = SelectFromModel(SGDClassifier(random_state=0), threshold='mean')
selector.fit(X, y)
selector.estimator_.coef_

array([[  8.64029104,  27.2851296 , -40.01819009, -17.73533424],
       [ -5.48888269, -58.79616709,  22.88584985, -54.14457159],
       [-81.28026953, -75.17372078, 130.76437145, 131.39608339]])

In [ ]:
np.array(iris.feature_names)[selector.get_support()]

array(['petal length (cm)', 'petal width (cm)'], dtype='<U17')